# Generated by Django 3.1.1 on 2021-01-06 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20210105_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='action',
            field=models.TextField(),
        ),
    ]
