# Generated by Django 3.1.5 on 2021-03-21 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_college_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='college',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='accounts.college'),
            preserve_default=False,
        ),
    ]
