# Generated by Django 3.1.5 on 2021-03-21 15:36

from django.db import migrations


def insert_data(apps, schema_editor):
    College = apps.get_model('accounts', 'College')
    College.objects.bulk_create([
        College(code='ADM', name='Administrative Offices'),
        College(code='ASE', name='College of Arts, Sciences and Education'),
        College(code='BED', name='Basic Education'),
        College(code='CCJ', name='College of Criminal Justice'),
        College(code='CCS', name='College of Computer Studies'),
        College(code='CEA', name='College of Engineering and Architecture'),
        College(code='MBA', name='College of Management, Business and Accountancy'),
        College(code='NAH', name='College of Nursing and Allied Health Sciences'),
    ])


def delete_data(apps, schema_editor):
    College = apps.get_model('accounts', 'College')
    College.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20210321_1535'),
    ]

    operations = [
        migrations.RunPython(insert_data, delete_data)
    ]
