# Generated by Django 3.1.5 on 2021-03-21 15:39

from django.db import migrations


def insert_data(apps, schema_editor):
    Department = apps.get_model('accounts', 'Department')
    College = apps.get_model('accounts', 'College')
    Department.objects.bulk_create([
        Department(code='CES', name='Community Extension Services', college=College.objects.get(pk=1)),
        Department(code='GUI', name='Guidance', college=College.objects.get(pk=1)),
        Department(code='LRA', name='Library Resource & Activity Center', college=College.objects.get(pk=1)),
        Department(code='MDC', name='Medical/Dental Clinic', college=College.objects.get(pk=1)),
        Department(code='HBS', name='Humanities and Behavioural Sciences', college=College.objects.get(pk=2)),
        Department(code='LMS', name='Languages, Literature and Communications, Math and Sciences', college=College.objects.get(pk=2)),
        Department(code='PLE', name='Physical Education', college=College.objects.get(pk=2)),
        Department(code='TED', name='Teacher Education', college=College.objects.get(pk=2)),
        Department(code='GRD', name='Graduate Studies', college=College.objects.get(pk=2)),
        Department(code='ELM', name='Elementary', college=College.objects.get(pk=3)),
        Department(code='JHS', name='Junior High School', college=College.objects.get(pk=3)),
        Department(code='SHS', name='Senior High School', college=College.objects.get(pk=3)),
        Department(code='CRM', name='Criminology', college=College.objects.get(pk=4)),
        Department(code='CMS', name='Computer Science', college=College.objects.get(pk=5)),
        Department(code='INT', name='Information Technology', college=College.objects.get(pk=5)),
        Department(code='GRD', name='Graduate Studies', college=College.objects.get(pk=5)),
        Department(code='ARC', name='Architecture', college=College.objects.get(pk=6)),
        Department(code='CLE', name='Civil Engineering', college=College.objects.get(pk=6)),
        Department(code='CHE', name='Chemical Engineering', college=College.objects.get(pk=6)),
        Department(code='CPE', name='Computer Engineering', college=College.objects.get(pk=6)),
        Department(code='ELE', name='Electrical Engineering', college=College.objects.get(pk=6)),
        Department(code='ECE', name='Electronics Engineering', college=College.objects.get(pk=6)),
        Department(code='ILE', name='Industrial Engineering', college=College.objects.get(pk=6)),
        Department(code='MLE', name='Mechanical Engineering', college=College.objects.get(pk=6)),
        Department(code='MGE', name='Mining Engineering', college=College.objects.get(pk=6)),
        Department(code='GRD', name='Graduate Studies', college=College.objects.get(pk=6)),
        Department(code='HTM', name='Hotel and Tourism Management', college=College.objects.get(pk=7)),
        Department(code='ACC', name='Accounting', college=College.objects.get(pk=7)),
        Department(code='OBA', name='Office Administration/Business', college=College.objects.get(pk=7)),
        Department(code='GRD', name='Graduate Studies', college=College.objects.get(pk=7)),
        Department(code='NRS', name='Nursing', college=College.objects.get(pk=8)),
        Department(code='PMY', name='Pharmacy', college=College.objects.get(pk=8)),
    ])


def delete_data(apps, schema_editor):
    Department = apps.get_model('accounts', 'Department')
    Department.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_init_college'),
    ]

    operations = [
        migrations.RunPython(insert_data, delete_data)
    ]
