# Generated by Django 3.1.5 on 2021-03-21 16:08

from django.db import migrations


def insert_data(apps, schema_editor):
    Course = apps.get_model("accounts", "Course")
    Department = apps.get_model('accounts', 'Department')
    Course.objects.bulk_create([
        Course(name='BS Psychology', department=Department.objects.get(pk=5)),
        Course(name='AB Communication', department=Department.objects.get(pk=6)),
        Course(name='AB English Language', department=Department.objects.get(pk=6)),
        Course(name='BS Biology', department=Department.objects.get(pk=6)),
        Course(name='BS Mathematics', department=Department.objects.get(pk=6)),
        Course(name='Bachelor of Elementary Education', department=Department.objects.get(pk=8)),
        Course(name='Bachelor of Secondary Education Major in English', department=Department.objects.get(pk=8)),
        Course(name='Bachelor of Secondary Education Major in Filipino', department=Department.objects.get(pk=8)),
        Course(name='Bachelor of Secondary Education Major in Mathematics', department=Department.objects.get(pk=8)),
        Course(name='Bachelor of Secondary Education Major in Science', department=Department.objects.get(pk=8)),
        Course(name='Bachelor of Multimedia Arts', department=Department.objects.get(pk=6)),
        Course(name='BS Computer Science', department=Department.objects.get(pk=14)),
        Course(name='BS Information Technology', department=Department.objects.get(pk=15)),
        Course(name='ARCH', department=Department.objects.get(pk=17)),
        Course(name='CE', department=Department.objects.get(pk=18)),
        Course(name='CHE', department=Department.objects.get(pk=19)),
        Course(name='CPE', department=Department.objects.get(pk=20)),
        Course(name='ECE', department=Department.objects.get(pk=22)),
        Course(name='EE', department=Department.objects.get(pk=21)),
        Course(name='EM', department=Department.objects.get(pk=25)),
        Course(name='IE', department=Department.objects.get(pk=23)),
        Course(name='BS Mechanical Engineering', department=Department.objects.get(pk=24)),
        Course(name='BS Mechanical Engineering with Mechatronics', department=Department.objects.get(pk=24)),
        Course(name='BS Accountancy', department=Department.objects.get(pk=28)),
        Course(name='BS Management Accounting', department=Department.objects.get(pk=28)),
        Course(name='BS Accounting Information Systems', department=Department.objects.get(pk=28)),
        Course(name='BS Hospitality Management', department=Department.objects.get(pk=27)),
        Course(name='BS Tourism Management', department=Department.objects.get(pk=27)),
        Course(name='Bachelor in Public Administration', department=Department.objects.get(pk=29)),
        Course(name='BS Office Administration', department=Department.objects.get(pk=29)),
        Course(name='BS Business Administration Major in Banking and Financial Management', department=Department.objects.get(pk=28)),
        Course(name='BS Business Administration Major in Business Analytics', department=Department.objects.get(pk=29)),
        Course(name='BS Business Administration Major in General Business Management', department=Department.objects.get(pk=29)),
        Course(name='BS Business Administration Major in Human Resource Management', department=Department.objects.get(pk=27)),
        Course(name='BS Business Administration Major in Marketing Management', department=Department.objects.get(pk=29)),
        Course(name='BS Business Administration Major in Operations Management', department=Department.objects.get(pk=29)),
        Course(name='BS Business Administration Major in Quality Management', department=Department.objects.get(pk=29)),
        Course(name='Nursing', department=Department.objects.get(pk=31)),
    ])


def delete_data(apps, schema_editor):
    Course = apps.get_model('accounts', 'Course')
    Course.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_course_department'),
    ]

    operations = [
        migrations.RunPython(insert_data, delete_data)
    ]
