# Generated by Django 3.1.5 on 2021-08-06 19:22

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_init_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('landing_page', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
        ),
    ]
