# Generated by Django 3.1.5 on 2021-08-06 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_auto_20210806_1929'),
    ]

    operations = [
        migrations.RenameField(
            model_name='setting',
            old_name='landing_page',
            new_name='value',
        ),
        migrations.AddField(
            model_name='setting',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='date_updated',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='name',
            field=models.CharField(default='08/06/2021', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='setting',
            name='set_by',
            field=models.ForeignKey(default='12', on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.user'),
            preserve_default=False,
        ),
    ]
