# Generated by Django 3.1.5 on 2021-08-06 19:59

from django.db import migrations


def insert_data(apps, schema_editor):
    Setting = apps.get_model("accounts", "Setting")
    Setting.objects.bulk_create([
        Setting(name='landing_page', value='<h1>IPAMS</h1><label class="card-subtitle mb-2 text-muted">Intellectual Property Asset Management System</label><p style="margin-top:20px"> is a tool for managing and organizing intellectual properties which are an essential part to the institution.</p>'),
    ])


def delete_data(apps, schema_editor):
    Setting = apps.get_model('accounts', 'Setting')
    Setting.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_auto_20210806_1959'),
    ]

    operations = [
        migrations.RunPython(insert_data, delete_data)
    ]
