# Generated by Django 4.1.3 on 2022-11-09 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='year_completed',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
    ]
