# Generated by Django 4.0.3 on 2022-03-18 05:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
