# Generated by Django 3.1.1 on 2020-12-13 01:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_init_records'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchrecord',
            name='research',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='research', to='records.record'),
        ),
    ]
