# Generated by Django 4.1.3 on 2022-11-09 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_alter_record_year_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='isbn',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='isi',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='issn',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='name',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='year_published',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='abstract_filename',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='code',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
