# Generated by Django 3.1.1 on 2021-01-06 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_auto_20201213_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='community_extension',
            field=models.BooleanField(default=False),
        ),
    ]
