# Generated by Django 3.1.1 on 2021-01-07 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0004_record_community_extension'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='record_type',
            field=models.ForeignKey(blank=True, default=3, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='records.recordtype'),
        ),
    ]
