# Generated by Django 3.1.5 on 2021-03-14 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0005_auto_20210107_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='representative',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
