# Generated by Django 4.0.3 on 2022-05-13 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0005_alter_conference_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='abstract_filename',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='record',
            name='abstract_filesize',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recordupload',
            name='filename',
            field=models.CharField(default='', max_length=150),
        ),
    ]
