# Generated by Django 4.0.3 on 2022-05-18 07:11

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0006_record_abstract_filename_record_abstract_filesize_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='abstract',
            field=ckeditor.fields.RichTextField(default=''),
            preserve_default=False,
        ),
    ]
