# Generated by Django 3.1.5 on 2021-03-21 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0006_record_representative'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
