# Generated by Django 4.0.3 on 2022-05-18 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0007_alter_record_abstract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='abstract_file',
            field=models.FileField(blank=True, default='', null=True, upload_to='abstract/'),
        ),
    ]
