# Generated by Django 3.1.5 on 2021-08-06 18:15

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0007_record_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='abstract',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
