# Generated by Django 4.0.3 on 2022-05-19 10:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0008_alter_record_abstract_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='year_completed',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='year_started',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
