# Generated by Django 4.0.3 on 2022-05-19 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0013_alter_record_year_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='year_completed',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
