# Generated by Django 4.0.3 on 2022-05-19 15:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0014_alter_record_year_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='year_completed',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(1990), django.core.validators.MaxValueValidator(2121)]),
        ),
    ]
