# Generated by Django 4.0.3 on 2022-05-19 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0016_alter_record_year_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='year_accomplished',
        ),
        migrations.AlterField(
            model_name='record',
            name='abstract_filename',
            field=models.CharField(blank=True, default='', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='abstract_filesize',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
