# Generated by Django 4.0.3 on 2022-05-19 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0019_alter_record_year_started'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='year_started',
            field=models.CharField(default=2022, max_length=30),
        ),
    ]
