# Generated by Django 4.0.3 on 2022-05-19 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0021_alter_record_year_started'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='year_accomplished',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
