# Generated by Django 4.0.3 on 2022-05-19 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0022_record_year_accomplished'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='year_started',
        ),
    ]
