# Generated by Django 4.0.3 on 2022-06-03 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0023_remove_record_year_started'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='is_marked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='record',
            name='reason',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
