# Generated by Django 4.0.5 on 2022-06-09 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0025_recorddownloadrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='recorddownloadrequest',
            name='is_marked',
            field=models.BooleanField(default=False),
        ),
    ]
