# Generated by Django 4.0.5 on 2022-06-10 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0026_recorddownloadrequest_is_marked'),
    ]

    operations = [
        migrations.AddField(
            model_name='recorddownloadrequest',
            name='user',
            field=models.BooleanField(default=False),
        ),
    ]
