# Generated by Django 4.0.3 on 2022-04-06 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='student',
        ),
        migrations.AddField(
            model_name='notification',
            name='course',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
