# Generated by Django 4.0.3 on 2022-04-08 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_remove_notification_student_notification_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='to_adviser',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='to_ktto',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='to_rdco',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='to_student',
            field=models.BooleanField(default=False),
        ),
    ]
