# Generated by Django 4.0.3 on 2022-04-13 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_notification_recipient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='to_adviser',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='to_student',
        ),
    ]
